### ISSUE TITLE
Cannot connect to device after switching *back* to developer_mode

### ISSUE THREAD

**Issue by jklingen** [nemomobile/usb-moded#23]
I have noticed this while testing the latest changes for [USB Switch](https://github.com/jklingen/harbour-usb-switch):

After switching from `developer_mode` to another mode and then back to `developer_mode`, I can no longer connect to the device, neither via SSH nor to deploy an RPM package from the SailfishOS IDE. I need to replug the USB connector to be able to connect again. This happens with `dbus-send` as well as with `usb_moded_util`.
Is there something I can/should do to "clean up" when switching away from `developer_mode`?

Steps to reproduce:
1. Connect USB to device, choose "PC Suite"
2. Switch mode: `usb_moded_util -s developer_mode`
3. Try to SSH-connect to device -> works as expected
4. Switch mode: `usb_moded_util -s pc_suite`
5. Switch back: `usb_moded_util -s developer_mode`
6. Try to SSH-connect to device -> Connection refused

The result is the same when step 3 is omitted. Same goes for intially choosing "Developer Mode" in the SailfishOS UI and then proceeding with step 4.

Environment: 
* SailfishOS 1.1.1.27 (Vaarainjärvi) on Jolla
* USB moded 0.80.7 with `usb-moded-connection-sharing-android-config` installed

Please let me know if you need more info.

Thanks and best regards,
Jens

**Comment by philippedeswert** [comment]
I'll check. but are you sure it is not a stupid problem with the network connectivity itself? So the phone does things right, but your pc is not getting an ip or so. Anyway will play with it myself to see if there is something else wrong.

**Comment by jklingen** [comment]
Thanks for checking. I don't know in detail how these connections work under the hood, so I cannot be 100% sure. But I have been able to reproduce this on my Win8 machine as well as my Ubuntu 14 VM (hosted on the same machine), also tried a (Win7) Laptop which shows the same behavior.

I'll check again with an Ubuntu live CD, maybe it is actually a Windows issue.

**Comment by jklingen** [comment]
I have been able to reproduce this on Ubuntu 14 running from a live CD, so it's not a Windows problem. Maybe you will be able to reproduce it... Unfortunately I have no alternative SailfishOS devices to test with ;-)

**Comment by philippedeswert** [comment]
Tested it and indeed there seems to be an issue. The interface comes up nicely but seems there is a problem with the dhcp server. Need to check if there is an app-sync or systemd issue.

**Comment by jklingen** [comment]
Thanks for having a look at this and keeping me updated. Let me know if I can assist in any way.

**Comment by philippedeswert** [comment]
Should be fixed by this: https://github.com/nemomobile/usb-moded/commit/cc9687c6e2180155df9fa73ac689fd933090caaa Will need some more testing.

**Comment by philippedeswert** [comment]
Seems ok after testing. Will be shipped in usb-moded-0.81.4

**Comment by jklingen** [comment]
Wow, that was quick - thanks a lot :)
